# config.yaml

# Dataset Settings
dataset:
  name: "MSMARCO"
  data_dir: "data/msmarco"
  train_file: "train.tsv"
  dev_file: "dev.tsv"
  qrels_file: "qrels.tsv"
  tokenizer: "bert-base-uncased"

# Model Settings
model:
  input_dim: 768
  output_dim: 768
  type: "mlp"            # or "linear" for a fixed matrix
  hidden_dim: 512
  dropout: 0.1

# Training Hyperparameters
training:
  batch_size: 32
  num_epochs: 5
  learning_rate: 2e-5
  margin: 0.2
  weight_decay: 0.01
  max_grad_norm: 1.0
  optimizer: "adamw"
  scheduler: "linear"
  warmup_steps: 100

# Checkpointing
checkpoint:
  output_dir: "checkpoints"
  save_steps: 1000
  save_total_limit: 2

# Logging
logging:
  logging_dir: "logs"
  logging_steps: 50

# Evaluation
evaluation:
  top_k: [10, 100]
  metrics: ["MRR", "NDCG", "Recall"]

# Hardware
hardware:
  device: "cuda"  # or "cpu"
  num_workers: 4
  seed: 42
